CarDealership/CarDealership.UI/Controllers/AdminController.cs
using CarDealership.Data;
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


namespace CarDealership.UI.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        VehicleManager manager = VehicleManagerFactory.Create();
        // GET: Vehicle
        public ActionResult Vehicles()
        {
            var model = manager.GetAllVehicles();
            return View(model);
        }

        [HttpGet]
        public ActionResult AddVehicle()
        {
            var vehicleVM = new VehicleViewModel();
            vehicleVM.SetCarMakeItems(manager.GetAllMakes());
            vehicleVM.SetCarModelItems(manager.GetAllCarModels());
            vehicleVM.SetVehicleTypeItems(manager.GetAllTypes());
            vehicleVM.SetBodyStyleItems(manager.GetAllStyles());
            vehicleVM.SetExColorItems(manager.GetAllExColors());
            vehicleVM.SetIntColorItems(manager.GetAllIntColors());
            vehicleVM.SetTransmissionItems(manager.GetAllTransmissions());

            return View(vehicleVM);
        }
        [HttpPost]
        public ActionResult AddVehicle(VehicleViewModel vehicleVM)
        {
            if (string.IsNullOrEmpty(vehicleVM.Vehicle.Vin))
            {
                ModelState.AddModelError("Vin", "Please enter a vin.");
            }
            if (ModelState.IsValid)
            {
                manager.ConvertVehicleVmToVehicle(vehicleVM);
                return RedirectToAction("Vehicles");
            }
            else
            {
                return View(vehicleVM);
            }
        }

        [HttpGet]
        public ActionResult EditVehicle(int id)
        {
            var viewModel = manager.ConvertVehicleToVM(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditVehicle(VehicleViewModel viewmodel)
        {
            manager.ConvertVehicleVmToVehicle(viewmodel);
            return RedirectToAction("Vehicles");
        }

        public ActionResult Users()
        {
            var model = manager.GetAllUsers();
            return View(model);
        }

        [HttpGet]
        public ActionResult AddUser()
        {
            var userVM = new UserViewModel();
            userVM.SetRoleItems(manager.GetAllRoles());
            return View(userVM);
        }

        [HttpPost]
        public ActionResult AddUser(UserViewModel userVM)
        {
            manager.ConvertUserVMtoUserAdd(userVM);
            return RedirectToAction("Users");
        }

        [HttpGet]
        public ActionResult EditUser(string id)
        {
            var userToEdit = manager.GetUser(id);
            return View(manager.ConvertUserToVM(userToEdit));
            
        }

        [HttpPost]
        public ActionResult EditUser(UserViewModel userVM)
        {
            manager.ConvertUserVMtoUserEdit(userVM);
            return RedirectToAction("Users");
        }
        [HttpGet]
        public ActionResult DeleteUser(string id)
        {
            var user = manager.GetUser(id);
            return View(user);
        }

        [HttpPost]
        public ActionResult DeleteUser(User user)
        {
            manager.DisableUser(user.Id);
            return RedirectToAction("Users");
        }

        public ActionResult Specials()
        {
            var specials = manager.GetAllSpecials();
            return View(specials);
        }
        [HttpGet]
        public ActionResult AddSpecial()
        {
            return View();
        }

        public ActionResult AddSpecial(Promo special)
        {
            manager.AddSpecial(special);
            return View();
        }
        [HttpGet]
        public ActionResult Makes()
        {
            return View(manager.GetAllMakes());
        }

        [HttpGet]
        public ActionResult AddMake()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMake(CarMake newMake)
        {
            newMake.UserName = User.Identity.GetUserName(); 
            manager.AddCarMake(newMake);
            return RedirectToAction("Makes");
        }
        [HttpGet]
        public ActionResult Models()
        {
            return View(manager.GetAllCarModels());
        }

        [HttpGet]
        public ActionResult AddModel()
        {
            var carmodelVM = new CarModelViewModel();
            carmodelVM.SetCarMakeItems(manager.GetAllMakes());
            return View(carmodelVM);
        }

        [HttpPost]
        public ActionResult AddModel(CarModelViewModel newModel)
        {
            newModel.UserName = User.Identity.GetUserName();
            manager.ConvertCarModelVMtoCarModel(newModel);
            return RedirectToAction("Models");
        }

        //public JsonResult GetMakes()
        //{
        //    return Json(manager.GetAllMakes().ToList(), JsonRequestBehavior.AllowGet);
        //}

        public JsonResult GetModelsByMake(string makeId)
        {
            int id = Convert.ToInt32(makeId);
            var carModels = manager.GetModelsByMake(id);
            return Json(carModels);
        }

    }
}

CarDealership/CarDealership.UI/Controllers/VehicleController.cs
using CarDealership.Data;
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.UI.Controllers
{
    public class VehicleController : Controller
    {
        VehicleManager manager = VehicleManagerFactory.Create();
        // GET: Vehicle
        public ActionResult Vehicles()
        {
            var model = manager.GetAllVehicles();
            return View(model);
        }

        [HttpGet]
        public ActionResult AddVehicle()
        {
            var vehicleVM = new VehicleViewModel();
            vehicleVM.SetCarMakeItems(manager.GetAllMakes());
            vehicleVM.SetCarModelItems(manager.GetAllCarModels());
            vehicleVM.SetVehicleTypeItems(manager.GetAllTypes());
            vehicleVM.SetBodyStyleItems(manager.GetAllStyles());
            vehicleVM.SetExColorItems(manager.GetAllExColors());
            vehicleVM.SetIntColorItems(manager.GetAllIntColors());
            vehicleVM.SetTransmissionItems(manager.GetAllTransmissions());

            return View(vehicleVM);
        }
        [HttpPost]
        public ActionResult AddVehicle(VehicleViewModel vehicleVM)
        {
            if (string.IsNullOrEmpty(vehicleVM.Vehicle.Vin))
            {
                ModelState.AddModelError("Vin", "Please enter a vin.");
            }
            if (ModelState.IsValid)
            {
                manager.ConvertVehicleVmToVehicle(vehicleVM);
                return RedirectToAction("Vehicles");
            }
            else
            {
                return View(vehicleVM);
            }
        }

        [HttpGet]
        public ActionResult EditVehicle(int id)
        {
            var viewModel = manager.ConvertVehicleToVM(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditVehicle(VehicleViewModel viewmodel)
        {
            manager.ConvertVehicleVmToVehicle(viewmodel);
            return RedirectToAction("Vehicles");
        }
    }
}

CarDealership/CarDealership.UI/Controllers/VehiclesController.cs
using CarDealership.Data;
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.Cors;

namespace CarDealership.UI.Controllers
{
    [EnableCors(origins: "*", methods: "*", headers: "*")]
    public class VehiclesController : ApiController
    {
        VehicleManager manager = VehicleManagerFactory.Create();

        [Route("vehicles")]
        [AcceptVerbs("GET")]
        public IHttpActionResult GetAllVehicles()
        {
           return Ok(manager.GetAllVehicles());

        }

        [Route("vehicle")]
        [AcceptVerbs("POST")]
        public IHttpActionResult AddVehicle(Vehicle newVehicle)
        {
            manager.AddVehicle(newVehicle);
            return Created($"vehicle/{newVehicle.Vin}", newVehicle);
        }

        [Route("makes")]
        [AcceptVerbs("GET")]
        public IHttpActionResult GetVehicleMake()
        {
            return Ok(manager.GetAllMakes());
        }

        [Route("models")]
        [AcceptVerbs("GET")]
        public IHttpActionResult GetAllModels()
        {
            return Ok(manager.GetModels());
        }

    }
}

CarDealership/CarDealership.UI/Views/Vehicle/AddVehicle.cshtml
@model CarDealership.Models.VehicleViewModel
@{
    ViewBag.Title = "AddVehicle";
}

<h2>AddVehicle</h2>


<div class="row">
    <div class="col-xs-12">
        <h3>Add Major</h3>
        @Html.ActionLink("Return to List", "Vehicles", "Admin")
    </div>
</div>
@*<div class="row">
        <div class="col-xs-12">
            @using (Html.BeginForm())
            {
                @Html.ValidationSummary()
                <div class="form-group">
                    <label>Major</label>
                    @Html.TextBoxFor(m => m.MajorName, new { @class = "form-control", placeholder = "Major" })
                </div>
                <button type="submit" class="btn btn-sm btn-primary">Save</button>
            }
        </div>
    </div>*@
<div class="container">
    <div class="row">
        <h2>Create Vehicle</h2>
        @using (Html.BeginForm())
        {
            <div class="col-xs-4">
                <div class="row">
                    <div class="form-group">
                        <label>Make</label>
                        @Html.DropDownListFor(v => v.Vehicle.CarModel.CarMake.CarMakeId, Model.CarMakeItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.VehicleType.VehicleTypeId)
                        @Html.DropDownListFor(v => v.Vehicle.VehicleType.VehicleTypeId, Model.VehicleTypeItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Year)
                        @Html.TextBoxFor(v => v.Vehicle.Year, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.ExteriorColor)
                        @Html.DropDownListFor(v => v.Vehicle.ExteriorColor.ExteriorColorId, Model.ExteriorColorItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Mileage)
                        @Html.TextBoxFor(v => v.Vehicle.Mileage, new { @type = "number", @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Msrp)
                        @Html.TextBoxFor(v => v.Vehicle.Msrp, new { @type = "number", @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-xs-offset-1 col-xs-4">
                <div class="row">
                    <div class="form-group">
                        <label>Model</label>
                        @Html.DropDownListFor(v => v.Vehicle.CarModel.CarModelId, Model.CarModelItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Body Style</label>
                        @Html.DropDownListFor(v => v.Vehicle.BodyStyle.BodyStyleId, Model.BodyStyleItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Transmission</label>
                        @Html.DropDownListFor(v => v.Vehicle.Transmission.TransmissionId, Model.TransmissionItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Interior Color</label>
                        @Html.DropDownListFor(v => v.Vehicle.InteriorColor.InteriorColorId, Model.InteriorColorItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>VIN #</label>
                        @Html.TextBoxFor(v=>v.Vehicle.Vin, new { @class = "form-control"})
                    </div>
                    <div>
                        <label>Sale Price</label>
                        @Html.TextBoxFor(v => v.Vehicle.SalePrice, new { @type = "number", @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="form-group">
                        <label class="col-xs-12">Description</label>
                        @Html.TextAreaFor(v => v.Vehicle.Description, new { @class = "col-xs-12", @style = "width:100%" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save Vehicle</button>
                        @Html.ActionLink("Cancel", "Vehicles", "Vehicle", null, new { @class = "btn btn-danger"})
                    </div>
                </div>
            </div>
        }
        </div>
    </div>



CarDealership/CarDealership.UI/Views/Vehicle/EditVehicle.cshtml
@model CarDealership.Models.VehicleViewModel

@{
    ViewBag.Title = "EditVehicle";
}

<div class="container">
    <div class="row">
        <h2>Edit Vehicle</h2>
        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(v=>v.Vehicle.VehicleId)
            <div class="col-xs-4">
                <div class="row">
                    <div class="form-group">
                        <label>Make</label>
                        @Html.DropDownListFor(v => v.Vehicle.CarModel.CarMake.CarMakeId, Model.CarMakeItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.VehicleType.VehicleTypeId)
                        @Html.DropDownListFor(v => v.Vehicle.VehicleType.VehicleTypeId, Model.VehicleTypeItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Year)
                        @Html.TextBoxFor(v => v.Vehicle.Year, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.ExteriorColor)
                        @Html.DropDownListFor(v => v.Vehicle.ExteriorColor.ExteriorColorId, Model.ExteriorColorItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Mileage)
                        @Html.TextBoxFor(v => v.Vehicle.Mileage, new { @type = "number", @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Msrp)
                        @Html.TextBoxFor(v => v.Vehicle.Msrp, new { @type = "number", @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-xs-offset-1 col-xs-4">
                <div class="row">
                    <div class="form-group">
                        <label>Model</label>
                        @Html.DropDownListFor(v => v.Vehicle.CarModel.CarModelId, Model.CarModelItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Body Style</label>
                        @Html.DropDownListFor(v => v.Vehicle.BodyStyle.BodyStyleId, Model.BodyStyleItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Transmission</label>
                        @Html.DropDownListFor(v => v.Vehicle.Transmission.TransmissionId, Model.TransmissionItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Interior Color</label>
                        @Html.DropDownListFor(v => v.Vehicle.InteriorColor.InteriorColorId, Model.InteriorColorItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>VIN #</label>
                        @Html.TextBoxFor(v => v.Vehicle.Vin, new { @class = "form-control" })
                    </div>
                    <div>
                        <label>Sale Price</label>
                        @Html.TextBoxFor(v => v.Vehicle.SalePrice, new { @type = "number", @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="form-group">
                        <label class="col-xs-12">Description</label>
                        @Html.TextAreaFor(v => v.Vehicle.Description, new { @class = "col-xs-12", @style = "width:100%" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save Edit</button>
                        @Html.ActionLink("Cancel Edit", "Vehicles", "Vehicle", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>

CarDealership/CarDealership.UI/Views/Vehicle/Vehicles.cshtml
@model IEnumerable<CarDealership.Models.Vehicle>
@{
    ViewBag.Title = "Vehicles";
}
<div class="col-xs-12">
    <div class="row">
        @foreach (var v in Model)
        {
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">@v.Year @v.CarModel.CarMake.Manufacturer @v.CarModel.CarModelName</h3>
                </div>
                <div class="panel-body">
                    <div class="col-xs-3">

                    </div>
                    <div class="col-xs-3">
                        <p>Body Style: @v.BodyStyle.BodyStyleName</p>
                        <p>Trans: @v.Transmission.TransmissionType</p>
                        <p>Color: @v.ExteriorColor.ExteriorColorName</p>
                    </div>
                    <div class="col-xs-3">
                        <p>Interior Color: @v.InteriorColor.InteriorColorName</p>
                        <p>Mileage: @v.Mileage</p>
                        <p>VIN: @v.Vin</p>
                    </div>
                    <div class="col-xs-3">
                        <p>Sale Price : $@v.SalePrice</p>
                        <p>MSRP: $@v.Msrp</p>
                        @Html.ActionLink("Edit Vehicle", "EditVehicle", "Vehicle", new { id = v.VehicleId }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>