CarDealership/CarDealership.UI/Controllers/AdminController.cs
using CarDealership.Data;
using CarDealership.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


namespace CarDealership.UI.Controllers
{
    [Authorize(Roles ="admin")]
    public class AdminController : Controller
    {
        VehicleManager manager = VehicleManagerFactory.Create();
        // GET: Vehicle
        public ActionResult Vehicles()
        {
            var model = manager.GetAllVehicles();
            return View(model);
        }

        [HttpGet]
        public ActionResult AddVehicle()
        {
            var vehicleVM = new VehicleViewModel();
            vehicleVM.SetCarMakeItems(manager.GetAllMakes());
            vehicleVM.SetCarModelItems(manager.GetAllCarModels());
            vehicleVM.SetVehicleTypeItems(manager.GetAllTypes());
            vehicleVM.SetBodyStyleItems(manager.GetAllStyles());
            vehicleVM.SetExColorItems(manager.GetAllExColors());
            vehicleVM.SetIntColorItems(manager.GetAllIntColors());
            vehicleVM.SetTransmissionItems(manager.GetAllTransmissions());

            return View(vehicleVM);
        }
        [HttpPost]
        public ActionResult AddVehicle(VehicleViewModel vehicleVM)
        {
            if (string.IsNullOrEmpty(vehicleVM.Vehicle.Vin))
            {
                ModelState.AddModelError("Vin", "Please enter a vin.");
            }
            if (ModelState.IsValid)
            {
                manager.ConvertVehicleVmToVehicle(vehicleVM);
                return RedirectToAction("Vehicles");
            }
            else
            {
                return View(vehicleVM);
            }
        }

        [HttpGet]
        public ActionResult EditVehicle(int id)
        {
            var viewModel = manager.ConvertVehicleToVM(id);
            return View(viewModel);
        }

        [HttpPost]
        public ActionResult EditVehicle(VehicleViewModel viewmodel)
        {
            manager.ConvertVehicleVmToVehicle(viewmodel);
            return RedirectToAction("Vehicles");
        }

        public ActionResult Users()
        {
            var model = manager.GetAllUsers();
            return View(model);
        }

        [HttpGet]
        public ActionResult AddUser()
        {
            var userVM = new UserViewModel();
            userVM.SetRoleItems(manager.GetAllRoles());
            return View(userVM);
        }

        [HttpPost]
        public ActionResult AddUser(UserViewModel userVM)
        {
            manager.ConvertUserVMtoUserAdd(userVM);
            return RedirectToAction("Users");
        }

        [HttpGet]
        public ActionResult EditUser(string id)
        {
            var userToEdit = manager.GetUser(id);
            return View(manager.ConvertUserToVM(userToEdit));
            
        }

        [HttpPost]
        public ActionResult EditUser(UserViewModel userVM)
        {
            manager.ConvertUserVMtoUserEdit(userVM);
            return RedirectToAction("Users");
        }
        [HttpGet]
        public ActionResult DeleteUser(string id)
        {
            var user = manager.GetUser(id);
            return View(user);
        }

        [HttpPost]
        public ActionResult DeleteUser(User user)
        {
            manager.DisableUser(user.Id);
            return RedirectToAction("Users");
        }

        public ActionResult Specials()
        {
            var specials = manager.GetAllSpecials();
            return View(specials);
        }
        [HttpGet]
        public ActionResult AddSpecial()
        {
            return View();
        }

        public ActionResult AddSpecial(Promo special)
        {
            manager.AddSpecial(special);
            return View();
        }
        [HttpGet]
        public ActionResult Makes()
        {
            return View(manager.GetAllMakes());
        }

        [HttpGet]
        public ActionResult AddMake()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddMake(CarMake newMake)
        {
            newMake.UserName = User.Identity.GetUserName(); 
            manager.AddCarMake(newMake);
            return RedirectToAction("Makes");
        }
        [HttpGet]
        public ActionResult Models()
        {
            return View(manager.GetAllCarModels());
        }

        [HttpGet]
        public ActionResult AddModel()
        {
            var carmodelVM = new CarModelViewModel();
            carmodelVM.SetCarMakeItems(manager.GetAllMakes());
            return View(carmodelVM);
        }

        [HttpPost]
        public ActionResult AddModel(CarModelViewModel newModel)
        {
            newModel.UserName = User.Identity.GetUserName();
            manager.ConvertCarModelVMtoCarModel(newModel);
            return RedirectToAction("Models");
        }

        //public JsonResult GetMakes()
        //{
        //    return Json(manager.GetAllMakes().ToList(), JsonRequestBehavior.AllowGet);
        //}

        public JsonResult GetModelsByMake(string makeId)
        {
            int id = Convert.ToInt32(makeId);
            var carModels = manager.GetModelsByMake(id);
            return Json(carModels);
        }

    }
}

CarDealership/CarDealership.UI/Controllers/InventoryController.cs
using CarDealership.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CarDealership.UI.Controllers
{
    public class InventoryController : Controller
    {
        VehicleManager manager = VehicleManagerFactory.Create();
        // GET: Inventory
        [Route("Inventory/VehicleDetails/{id}")]
        public ActionResult VehicleDetails(int id)
        {
            var vehicleVM = manager.ConvertVehicleToVM(id);
            return View(vehicleVM);
        }

        public ActionResult NewVehicles()
        {
            var vehicles = manager.GetAllNewVehicles();
            return View(vehicles);
        }

        public ActionResult UsedVehicles()
        {
            var vehicles = manager.GetAllUsedVehicles();
            return View(vehicles);
        }
    }
}

CarDealership/CarDealership.UI/Views/Shared/ContactPartialView.cshtml
@model CarDealership.Models.ContactRequest
@{
    Layout = null;
}

<div class="container">
    <div class="row">
        <div class="col-xs-5">
            @using (Html.BeginForm())
            {

                @Vereyon.Web.FlashMessageHtmlHelper.RenderFlashMessages(Html)
                <div class="form-group">
                    <label>Name</label>
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Email</label>
                    @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <label>Phone</label>
                    @Html.TextBoxFor(m => m.Phone, new { @class = "form-control" })
                </div>
                <div class="form-group vinHide">
                    <label>Vehicle</label>
                    @Html.TextBoxFor(m => m.Vehicle.Vin, new { @readonly = "readonly", @class = "vinInput form-control" })
                </div>
                <div class="form-group">
                    <label>Message</label>
                    @Html.TextAreaFor(m => m.Message, new { @class = "form-control" })
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-danger">Submit</button>
                </div>
            }
        </div>
        <div class="col-xs-7">
            <div id="map">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2822.262754854713!2d-93.27401704927594!3d44.97897317360779!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x52b332907d76198f%3A0x47305550cfd48180!2sThe+Software+Guild!5e0!3m2!1sen!2sus!4v1510598921842" width="400" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
            </div>
            <address>
                15 S 5th St #600<br />
                Minneapolis, MN 554029<br />
                <abbr title="Phone">Sales:</abbr>
                111-555-1111<br />
                <abbr title="Phone">Service:</abbr>
                111-555-1112
            </address>
        </div>
    </div>
</div>


CarDealership/CarDealership.UI/Views/Shared/SearchPartialView.cshtml
@{
    Layout = null;
}

<form style="border: 1px solid #000;padding:15px;">
    <div class="row">
        <div class="col-xs-4">
            <label>Quick Search</label>
        </div>
        <div class="col-xs-4">
            <label>Price</label>
        </div>
        <div class="col-xs-4">
            <label>Year</label>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-4">
            <input class="form-control" type="text" id="makeModelYear" placeholder="Enter make, model, or year" />
        </div>
        <div class="col-xs-2">
            <select id="minPrice" class="form-control pricing">
                <option value="">No Min</option>
            </select>
        </div>
        <div class="col-xs-2">
            <select id="maxPrice" class="form-control pricing">
                <option value="">No Max</option>
            </select>

        </div>
        <div class="col-xs-2">
            <select id="minYear" class="form-control yearMade">
                <option value="">No Min</option>
            </select>
        </div>
        <div class="col-xs-2">
            <select id="maxYear" class="form-control yearMade">
                <option value="">No Max</option>
            </select>
        </div>
    </div>


    <div class="row" style="margin-top:15px;">
        <div class="col-xs-5">&nbsp;</div>
        <div class="col-xs-7">
            <button class="btn btn-danger" id="searchButton">Search</button>
        </div>
    </div>
</form>

CarDealership/CarDealership.UI/Views/Shared/UserPartialView.cshtml
@model CarDealership.Models.UserViewModel
@{
    Layout = null;
}

@using (Html.BeginForm())
{
   <div class="row">
       <div class="col-xs-4 form-group">
           <label>First Name</label>
           @Html.TextBoxFor(u=>u.User.FirstName, new {@class = "form-control" })
       </div>
       <div class="col-xs-4 form-group">
           <label>Last Name</label>
           @Html.TextBoxFor(u=>u.User.LastName, new { @class = "form-control"})
       </div>
   </div>
   <div class="row">
       <div class="col-xs-4 form-group">
           <label>Email</label>
           @Html.TextBoxFor(u=>u.User.Email, new { @class = "form-control"})
       </div>
       <div class="col-xs-4 form-group">
           <label>Role</label>
           @Html.DropDownListFor(u=>u.Role.Id, Model.RoleItems, "-Choose One-", new { @class = "form-control"})
       </div>
   </div>
   <div class="row">
       <div class="col-xs-4 form-group">
           <label>Password</label>
           @Html.TextBoxFor(u=>u.Password, new { @class = "form-control"})
       </div>
       <div class="col-xs-4 form-group">
           <label>Confirm Password</label>
           @Html.TextBoxFor(u=>u.ConfirmPassword, new { @class ="form-control"})
       </div>
   </div>
   <div class="row">
       <div class="col-xs-2 form-group">
           <button class="btn btn-danger" type="submit">Save User</button>
       </div>
   </div>
}

CarDealership/CarDealership.UI/Views/Shared/VehicleDetailsPartialView.cshtml
@model CarDealership.Models.InvoiceViewModel
@{
    Layout = null;
}

<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">@Model.Vehicle.Year @Model.Vehicle.CarModel.CarMake.Manufacturer @Model.Vehicle.CarModel.CarModelName</h3>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-3">
                <p>Picture Goes here!</p>
            </div>
            <div class="col-xs-3">
                <p>Body Style: @Model.Vehicle.BodyStyle.BodyStyleName</p>
                <p>Trans: @Model.Vehicle.Transmission.TransmissionType</p>
                <p>Color: @Model.Vehicle.ExteriorColor.ExteriorColorName</p>
            </div>
            <div class="col-xs-3">
                <p>Interior Color: @Model.Vehicle.InteriorColor.InteriorColorName</p>
                <p>Mileage: @Model.Vehicle.Mileage</p>
                <p>VIN: @Model.Vehicle.Vin</p>
            </div>
            <div class="col-xs-3">
                <p>Sale Price : $@Model.Vehicle.SalePrice</p>
                <p>MSRP: $@Model.Vehicle.Msrp</p>
            </div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-xs-offset-3">
                <p>Description: $@Model.Vehicle.Description</p>
            </div>
        </div>
    </div>
    <div class="panel-body col-xs-offset-9">
        <button class="btn btn-danger contactButton form-control" @("onclick=contactAction(" + Model.Vehicle.VehicleId + ")")>Change Me</button>
    </div>
</div>

CarDealership/CarDealership.UI/Views/Shared/VehicleFormPartialView.cshtml
@model CarDealership.Models.VehicleViewModel
@{
    Layout = null;

}

@*<div class="container">
    <div class="row">
        <h2>Create Vehicle</h2>
        @using (Html.BeginForm())
        {*@
                <div class="row">
                    <div class="form-group">
                        <label>Make</label>
                        @Html.DropDownListFor(v => v.Vehicle.CarModel.CarMake.CarMakeId, Model.CarMakeItems, "-Choose One-", new { @class = "form-control", @id = "carMakeDropdown" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.VehicleType.VehicleTypeId)
                        @Html.DropDownListFor(v => v.Vehicle.VehicleType.VehicleTypeId, Model.VehicleTypeItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Year)
                        @Html.TextBoxFor(v => v.Vehicle.Year, new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.ExteriorColor)
                        @Html.DropDownListFor(v => v.Vehicle.ExteriorColor.ExteriorColorId, Model.ExteriorColorItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Mileage)
                        @Html.TextBoxFor(v => v.Vehicle.Mileage, new { @type = "number", @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(v => v.Vehicle.Msrp)
                        @Html.TextBoxFor(v => v.Vehicle.Msrp, new { @type = "number", @class = "form-control" })
                    </div>
                    <div class="form-group">
                        @Html.CheckBoxFor(v => v.Vehicle.IsVehicleSold)
                        @Html.LabelFor(m => m.Vehicle.IsVehicleSold, new { @style = "font-weight:bold" })
                    </div>
                </div>
            @*<div class="col-xs-offset-1 col-xs-4">
                <div class="row">
                    <div class="form-group">
                        <label>Model</label>
                        @Html.DropDownListFor(v => v.Vehicle.CarModel.CarModelId, new SelectList(Model.CarModelItems, "Value", "Text"), "-Choose One-", new { @class = "form-control", @id = "carModelDropdown" })
                    </div>
                    <div class="form-group">
                        <label>Body Style</label>
                        @Html.DropDownListFor(v => v.Vehicle.BodyStyle.BodyStyleId, Model.BodyStyleItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Transmission</label>
                        @Html.DropDownListFor(v => v.Vehicle.Transmission.TransmissionId, Model.TransmissionItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>Interior Color</label>
                        @Html.DropDownListFor(v => v.Vehicle.InteriorColor.InteriorColorId, Model.InteriorColorItems, "-Choose One-", new { @class = "form-control" })
                    </div>
                    <div class="form-group">
                        <label>VIN #</label>
                        @Html.TextBoxFor(v => v.Vehicle.Vin, new { @class = "form-control" })
                    </div>
                    <div>
                        <label>Sale Price</label>
                        @Html.TextBoxFor(v => v.Vehicle.SalePrice, new { @type = "number", @class = "form-control" })
                    </div>
                </div>
            </div>
            <div class="col-xs-9">
                <div class="row">
                    <div class="form-group">
                        <label class="col-xs-12">Description</label>
                        @Html.TextAreaFor(v => v.Vehicle.Description, new { @class = "col-xs-12", @style = "width:100%" })
                    </div>
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">Save Vehicle</button>
                        @Html.ActionLink("Cancel", "Vehicles", "Admin", null, new { @class = "btn btn-danger" })
                    </div>
                </div>
            </div>
        }
    </div>
</div>*@

CarDealership/CarDealership.UI/Views/Shared/VehicleResultsPartialView.cshtml
@{
    Layout = null;
}

    <div class="row">
        @foreach (var v in Model)
        {
            <div class="panel panel-default" @("id=vehicle"+ v.VehicleId) hidden>
                <div class="panel-heading">
                    <h3 class="panel-title">@v.Year @v.CarModel.CarMake.Manufacturer @v.CarModel.CarModelName</h3>
                </div>
                <div class="panel-body">
                    <div class="col-xs-3">
                        <p>Picture Goes here!</p>
                    </div>
                    <div class="col-xs-3">
                        <p>Body Style: @v.BodyStyle.BodyStyleName</p>
                        <p>Trans: @v.Transmission.TransmissionType</p>
                        <p>Color: @v.ExteriorColor.ExteriorColorName</p>
                    </div>
                    <div class="col-xs-3">
                        <p>Interior Color: @v.InteriorColor.InteriorColorName</p>
                        <p>Mileage: @v.Mileage</p>
                        <p>VIN: @v.Vin</p>
                    </div>
                    <div class="col-xs-3">
                        <p>Sale Price : $@v.SalePrice</p>
                        <p>MSRP: $@v.Msrp</p>
                        <button class="btn btn-danger vehicleButton"  @("onclick=vehicleAction(" + v.VehicleId + ")")>Change Me</button>
                    </div>
                </div>
            </div>
        }
    </div>

CarDealership/CarDealership.UI/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sales></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Reynolds Automotive", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("New Inventory", "NewVehicles", "Inventory")</li>
                    <li>@Html.ActionLink("Used Inventory", "UsedVehicles", "Inventory")</li>
                    <li>@Html.ActionLink("Specials", "Specials", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                    <li>@Html.ActionLink("Admin", "Vehicles", "Admin")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sales</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>


CarDealership/CarDealership.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <!-- Latest compiled and minified CSS -->
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Reynolds Automotive", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @if (User.IsInRole("admin"))
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("New Inventory", "NewVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Used Inventory", "UsedVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Specials", "Specials", "Home")</li>
                        <li>@Html.ActionLink("Contact", "ContactUs", "Home")</li>
                        <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Admin
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu" id="adminDropdown" value="Admin">
                                <li>@Html.ActionLink("Vehicles", "Vehicles", "Admin")</li>
                                <li>@Html.ActionLink("Models", "Models", "Admin")</li>
                                <li>@Html.ActionLink("Makes", "Makes", "Admin")</li>
                                <li>@Html.ActionLink("Reports", "Index", "Reports")</li>
                                <li>@Html.ActionLink("Users", "Users", "Admin")</li>
                            </ul>
                        </li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Account
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>@Html.ActionLink("UpdatePassword", "UpdatePassword", "Auth")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Logout", "Logout", "Auth") </li>
                            </ul>
                        </li>
                    }
                    else if (User.IsInRole("sales"))
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("New Inventory", "NewVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Used Inventory", "UsedVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Specials", "Specials", "Home")</li>
                        <li>@Html.ActionLink("Contact", "ContactUs", "Home")</li>
                        <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                        <li class="dropdown">
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                Account
                                <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li>@Html.ActionLink("UpdatePassword", "UpdatePassword", "Auth")</li>
                                <li class="divider"></li>
                                <li>@Html.ActionLink("Logout", "Logout", "Auth") </li>
                            </ul>
                        </li>
                    }
                    else
                    {
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("New Inventory", "NewVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Used Inventory", "UsedVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Specials", "Specials", "Home")</li>
                        <li>@Html.ActionLink("Contact", "ContactUs", "Home")</li>
                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

CarDealership/CarDealership.UI/Views/Shared/_SalesLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sales></title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Reynolds Automotive", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("New Inventory", "NewVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Used Inventory", "UsedVehicles", "Inventory")</li>
                        <li>@Html.ActionLink("Specials", "Specials", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                        <li>@Html.ActionLink("Sales", "Index", "Sales")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Sales</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
                        @Scripts.Render("~/bundles/bootstrap")
                        @RenderSection("scripts", required: false)
                    </body>
                </html>